# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: plugin-safe-redirect
spec:
  enabled: true
  requires: ">=2.17.0"
  author:
    name: 小聂
    website: https://xiaonie.me
  logo: logo.svg
  homepage: https://github.com/nieshilin/plugin-safe-redirect#readme
  repo: https://github.com/nieshilin/plugin-safe-redirect
  issues: https://github.com/nieshilin/plugin-safe-redirect/issues
  displayName: "安全跳转助手"
  description: "为文章外部链接提供安全跳转中间页，支持自定义样式、图标和主题，有效防止钓鱼攻击。"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-safe-redirect/blob/main/LICENSE"
  settingName: "plugin-safe-redirect-setting"
  configMapName: "plugin-safe-redirect-config"
